# vim:ft=ansible:
- name: add homebrew tap repository
  homebrew_tap: tap="{{ item.name }}" state=present
  with_items:
    - "{{ homebrew_tap }}"
  tags: install-homebrew_tap

- name: install homebrew packages
  homebrew:
    name: "{{ item.name }}"
    state: present
    install_options: "{{ item.install_options | default() }}"
  with_items:
    - "{{ homebrew_packages }}"
  tags: install-homebrew-packages

- name: install homebrew cask packages
  homebrew_cask:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ homebrew_cask_packages }}"
  tags: install-homebrew_cask-packages

